.TH DASHT\-DOCSETS 1               2020\-05\-16                            2.4.0
.SH NAME
.PP
dasht\-docsets \- lists installed Dash \[la]https://kapeli.com/dash\[ra] docsets
.SH SYNOPSIS
.PP
\fB\fCdasht\-docsets\fR [\fINAME\fP\&...]
.SS Examples
.TP
\fB\fCdasht\-docsets\fR
Lists all installed Dash \[la]https://kapeli.com/dash\[ra] docsets.
.TP
\fB\fCdasht\-docsets\fR sh
Lists installed Dash \[la]https://kapeli.com/dash\[ra] docsets whose names contain "sh".
.TP
\fB\fCdasht\-docsets\fR sh 'c$'
Lists installed Dash \[la]https://kapeli.com/dash\[ra] docsets whose names contain "sh" or end in "c".
.SH DESCRIPTION
.PP
Lists the names of Dash \[la]https://kapeli.com/dash\[ra] docsets installed under \fB\fCDASHT_DOCSETS_DIR\fR\&.  The
listing is optionally filtered to include only those docset names that match
the \fINAME\fP 
.BR regex (7) 
patterns, if specified, before it is printed to stdout.
.SH ENVIRONMENT
.TP
\fB\fCDASHT_DOCSETS_DIR\fR
Defines the filesystem location where your Dash \[la]https://kapeli.com/dash\[ra] docsets are installed.
If undefined, its value is assumed to be \fB\fC$XDG_DATA_HOME/dasht/docsets/\fR
or, if \fB\fCXDG_DATA_HOME\fR is undefined, \fB\fC$HOME/.local/share/dasht/docsets/\fR\&.
.SH SEE ALSO
.PP
.BR dasht-docsets-install (1), 
.BR dasht-docsets-update (1), 
.BR dasht-docsets-remove (1),
.BR dasht (1), 
Dash \[la]https://kapeli.com/dash\[ra]
.SH AUTHOR
.PP
Written in 2016 by Suraj N. Kurapati \[la]https://github.com/sunaku/dasht\[ra]
Distributed under the terms of the ISC license (see the LICENSE file).
